learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

    # File upload examples
    path('upload/', views.upload_file, name='upload_file'),
    path('img_upload/', views.img_upload, name='img_upload'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls. -http://localhost:8000/users/login/
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register')
]

learning_logs/models.py
import os

from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model. """
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string rep of the model"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        return f"{self.text[:50]}"


class Image(models.Model):
    img_type = models.CharField(max_length=100, default='sample')
    img_class = models.CharField(max_length=100, default='unclassified')
    img_dir = models.ImageField(upload_to='images/')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation the type of model. """
        return f"{self.id}_{self.img_dir.name.split('/')[-1]}"


#  Clean-up, delete image file on delete of Image instances.
@receiver(pre_delete, sender=Image)
def delete_image_file(sender, instance, **kwargs):
    # Check if the image field has a value
    if instance.img_dir:
        # Get the path of the image file
        image_path = instance.img_dir.path
        # Check if the image file exists and delete it
        if os.path.exists(image_path):
            os.remove(image_path)

learning_logs/forms.py
from django import forms
from .models import Topic, Entry, Image


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['img_dir']
        labels = {'img_dir': ''}

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm, ImageForm
from django.http import Http404


# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    #topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    # Make sure the tipic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        # Ensures all fields are fill out etc.
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            # Saves to db
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def img_upload(request):
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = ImageForm()
    else:
        # POST data submitted; process data.
        form = ImageForm(data=request.POST, files=request.FILES)
        # Ensures all fields are fill out etc.
        if form.is_valid():
            form.save()
            return render(request, 'learning_logs/upload_success.html')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/img_upload.html', context)


def upload_file(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['file']
        # Handle the uploaded file (e.g., save it to the server or process it)
        # For example:
        with open('uploaded_file.txt', 'wb+') as destination:
            for chunk in uploaded_file.chunks():
                destination.write(chunk)
        return render(request, 'learning_logs/upload_success.html')
    return render(request, 'learning_logs/upload_file.html')

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <h2>This is the edit entry page!</h2>


  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/img_upload.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Upload an Image</h2>
{% endblock page_header %}

{% block content %}

    <form method='post' action = "{% url 'learning_logs:img_upload' %}" enctype="multipart/form-data">
        <!-- cross-site request forgery -->
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <!-- tells Django to render all the form elements in paragraph format -->
            <button name="submit" class="btn btn-primary">Upload</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>
      <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
  </div>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

  <h4>Add a new entry</h4>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p}}
    <button name='submit'>Add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <h2>Add a new topic</h2>
    <form action = "{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a></p>

    {% for entry in entries %}
      <div class="card mb-3">

        <h4 class="card-header">
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
        </h4>
        <div class="card-body">
          <p>{{ entry.text|linebreaks }}</p>
        </div>

      </div>
    {% empty %}
      <p>There are no entries for this topic yet</p>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li><h4>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h4></li>
    {% empty %}
      <li><h4>No topics have been added yet</h4></li>
    {% endfor %}
  </ul>
  <div>
    <br>
    <h6><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h6>
    <h6><a href="{% url 'learning_logs:img_upload' %}">Upload an Image</a></h6>
  </div>
{% endblock content %}

learning_logs/templates/learning_logs/upload_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Django Project</title>
    <!-- Link to your CSS file -->
    <style>
        /* styles.css */
        .upload-form {
            margin-bottom: 20px;
        }

        .upload-form input[type="file"] {
            display: none;
        }

        .upload-form label {
            background-color: #3498db;
            color: #fff;
            padding: 10px 15px;
            border-radius: 5px;
            cursor: pointer;
        }

        .upload-form button[type="submit"] {
            background-color: #2ecc71;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <!-- form class="upload-form" method="post" enctype="multipart/form-data" -->
    <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file">Choose a file</label>
        <input type="file" name="file" id="file">
        <button type="submit">Upload</button>
    </form>
</body>
</html>

learning_logs/templates/learning_logs/upload_success.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <div class="jumbotron">
    <h2 class="display-4">Congratulations!</h2>
      <p class="lead">Your file has been uploaded successfully</p>
  </div>
{% endblock content %}